package co.edu.uniquindio.clinica.modelo.enums;

public enum Especialidad {

    CARDIOLOGIA,
    PEDIATRIA,
    DERMATOLOGIA,
    NEUROLOGIA,
    ODONTOLOGIA,
    UROLOGIA,
    ANGIOLOGIA,
    GASTROENTEROLOGIA,
    GINECOLOGIA,
    OBSTETRICIA,
    MEDICINA_INTERNA,
    NEFROLOGIA,
    NEUMOLOGIA,
    OFTALMOLOGIA,
    ORTOPEDIA,
    OTORRINOLARINGOLOGIA,
    PSIQUIATRIA,
    ONCOLOGIA

}
